codi1, uni1, valor1 = input().split()
codi1 = int(codi1)
uni1 = int(uni1)
valor1 = float(valor1)
codi2, uni2, valor2 = input().split()
codi2 = int(codi2)
uni2 = int(uni2)
valor2 = float(valor2)
total = (uni1 * valor1) + (uni2 * valor2)
print(f'VALOR A PAGAR: R$ {total:.2f}')
